import streamlit as st 
def app() :
    ## Judul Halaman Aplikasi
    st.title("Aplikasi Prediksi Penyakit Batu Ginjal")
    
    st.write("Batu ginjal adalah kondisi medis yang umum terjadi saat mineral dan garam tertentu mengendap dan membentuk massa keras di dalam ginjal. Proses ini dapat menyebabkan rasa sakit yang parah dan, dalam beberapa kasus, bahkan infeksi serius. Gejala yang umum terkait dengan batu ginjal termasuk nyeri tiba-tiba yang parah di bagian bawah punggung atau perut, serta rasa tidak nyaman saat buang air kecil. Meskipun batu ginjal bisa terjadi pada siapa saja, faktor risiko seperti pola makan, dehidrasi, riwayat keluarga, dan kondisi medis tertentu seperti obesitas atau penyakit tertentu dapat meningkatkan kemungkinan seseorang mengalaminya.")
    
    st.write("Diagnosis batu ginjal sering kali melibatkan serangkaian tes medis, termasuk pemindaian pencitraan seperti CT scan, X-ray, atau ultrasound. Dokter juga mungkin akan melakukan analisis urine dan darah untuk menentukan jenis batu ginjal yang terbentuk dan mencari tahu faktor-faktor yang mungkin menyebabkannya. Melalui diagnosis yang tepat, penanganan dapat diberikan sesuai dengan jenis batu ginjal yang terbentuk serta tingkat keparahan gejalanya.")
    
    st.write("Program prediksi yang dibangun dengan menggunakan platform Streamlit bertujuan untuk membantu mengidentifikasi kemungkinan seseorang rentan terkena penyakit batu ginjal. Dengan memanfaatkan data tentang faktor-faktor seperti riwayat kesehatan, gaya hidup, pola makan, dan informasi medis lainnya, program ini dapat memberikan prediksi atau perkiraan tingkat risiko seseorang terhadap penyakit ini. Tujuan akhir dari program ini adalah untuk memberikan informasi yang berguna kepada individu maupun tenaga medis, sehingga langkah-langkah pencegahan atau perawatan dapat diambil lebih awal untuk mengurangi risiko atau mengelola kondisi batu ginjal dengan lebih efektif.")